In [8]:
a=5

In [9]:
b=3

In [10]:
print(a)

5


In [11]:
def my_fun():
    print("hello")
my_fun()

hello


In [12]:
def add(a,b):
    print(a+b)


In [14]:
add(2,6)

8


In [15]:
a=[1,2,3,4,5,6,7,8]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8]


In [16]:
text="hello world hai"

In [17]:
text.split()

['hello', 'world', 'hai']

In [18]:
text="hel,lo wor,ld hai"

In [20]:
text.split(",")

['hel', 'lo wor', 'ld hai']

In [21]:
ab=text.split()

In [22]:
ab[0]

'hel,lo'

In [23]:
ab[-1]

'hai'

In [25]:
x=[1,2,6,3,4,5]
for i in x:
    print(i)

1
2
6
3
4
5


In [28]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [31]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [36]:
list1=[]
t=int(input("enter the size of array"))
for i in range(0,t):
    l=input("enter the values:")
    list1.append(l)



enter the size of array3
enter the values:1
enter the values:2
enter the values:3


# 

In [38]:
list1

['1', '2', '3']

In [39]:
import math
r=2
rs=math.pi*r*r
print(rs)

12.566370614359172


In [40]:
from new import pack
sum(2,3)

ModuleNotFoundError: No module named 'new'

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
z=np.zeros((2,3))

In [5]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
r=np.arange(0,10,2)

In [7]:
r


array([0, 2, 4, 6, 8])

In [10]:
a

array([1, 2, 3])

In [8]:
b=np.array([4,5,6])

In [9]:
a+b

array([5, 7, 9])

In [11]:
np.mean(a)

2.0

In [12]:
np.max(a)

3

In [13]:
c=np.array([
    [1,2],
    [3,4]])

In [14]:
c

array([[1, 2],
       [3, 4]])

In [15]:
d=np.array([
    [4,8],
    [6,9]
])

In [16]:
c+d

array([[ 5, 10],
       [ 9, 13]])

In [19]:
e=c*d

In [20]:
e

array([[ 4, 16],
       [18, 36]])

In [21]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [22]:
c.T

array([[1, 3],
       [2, 4]])

In [23]:
c

array([[1, 2],
       [3, 4]])

In [24]:
d

array([[4, 8],
       [6, 9]])

In [25]:
f

array([[16, 26],
       [36, 60]])

In [26]:
f.T

array([[16, 36],
       [26, 60]])

In [27]:
print("\n matrix 1:\n",c)
print("\n matrix 2:\n",d)
print("\n Addition:\n",c+d)
print("\n substraction:\n",c-d)
print("\n Multiplication(Element wise):\n",c*d)
print("\n Dot Multiplication(row x column):\n",f)
print("\n Transpose:\n",f.T)


 matrix 1:
 [[1 2]
 [3 4]]

 matrix 2:
 [[4 8]
 [6 9]]

 Addition:
 [[ 5 10]
 [ 9 13]]

 substraction:
 [[-3 -6]
 [-3 -5]]

 Multiplication(Element wise):
 [[ 4 16]
 [18 36]]

 Dot Multiplication(row x column):
 [[16 26]
 [36 60]]

 Transpose:
 [[16 36]
 [26 60]]
